# Generated by Django 4.2.23 on 2025-08-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClaimList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_name", models.CharField(max_length=100)),
                ("billed_amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("paid_amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("status", models.CharField(max_length=100)),
                ("insurer_name", models.CharField(max_length=100)),
                ("discharge_date", models.DateField()),
            ],
        ),
    ]
