# Generated by Django 4.2.23 on 2025-08-23 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClaimDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("denial_reason", models.CharField(max_length=255)),
                ("cpt_codes", models.CharField(max_length=100)),
                (
                    "claim_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.claimlist"
                    ),
                ),
            ],
        ),
    ]
