# Generated by Django 4.2.23 on 2025-09-01 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_user_note_annotation_flag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_first_name", models.CharField(max_length=255)),
                ("employee_last_name", models.CharField(max_length=255)),
                ("employee_type", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="annotation",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.employee"
            ),
        ),
        migrations.AlterField(
            model_name="flag",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.employee"
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.employee"
            ),
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
