# Generated by Django 4.2.23 on 2025-09-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_employee_alter_annotation_user_id_alter_flag_user_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="employee_password",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
