# Generated by Django 4.2.23 on 2025-09-08 21:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_employee_employee_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="employee_username",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
