# Generated by Django 4.2.23 on 2025-09-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_employee_employee_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="employee_username",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
