# Generated by Django 4.2.23 on 2025-09-10 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_employee_employee_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flag",
            name="flag",
        ),
    ]
