# Generated by Django 4.2.23 on 2025-09-10 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_flag_flag"),
    ]

    operations = [
        migrations.RenameField(
            model_name="annotation",
            old_name="user_id",
            new_name="employee_id",
        ),
        migrations.RenameField(
            model_name="flag",
            old_name="user_id",
            new_name="employee_id",
        ),
        migrations.RenameField(
            model_name="note",
            old_name="user_id",
            new_name="employee_id",
        ),
        migrations.AlterUniqueTogether(
            name="flag",
            unique_together={("claim_id", "employee_id")},
        ),
    ]
