# Generated by Django 4.2.23 on 2025-09-11 21:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_rename_user_id_annotation_employee_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="claimdetail",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="claimdetail",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="claimlist",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="claimlist",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
